### ISSUE TITLE
Any plan for releasing the code

### ISSUE THREAD

**Issue by zouhaoa** [aleksandrkim61/EagerMOT#1]
Hi!
Thanks for your wonderful work!

I'm wondering if there is a plan for releasing the code of EagerMOT?

Thanks!

**Comment by aleksandrkim61** [comment]
Hi, thank you for your interest!

The code will be pushed very soon. As stated in the README, the plan was to release it shortly before ICRA, which starts on June 1st. I started removing unnecessary code bits last week and will most likely push the repo **this weekend**. Consider _watching_ the repo to be notified when this happens.
