### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by lx-ynu** [aleksandrkim61/EagerMOT#10]
Hello, thank you for your work, I want to know how to visualize the results, where is the code?

**Comment by aleksandrkim61** [comment]
Hi,

I observed that people working on tracking usually already have their own visualization setup, so the code I was using for visualizations was not prepared or released. 

I might find some time later to release a simple version of my visualizer but it's not in the immediate plans. There did not seem to be any demand for that.

Perhaps you can find some repository that deals with 3D tracking and use their visualization code. The reported 3D MOT results follow a predefined format, so most implementations should be compatible.

**Comment by gayathri81** [comment]
Hello @ynlx 
Did you get to now how to visualize the results?

**Comment by joshphoo** [comment]
Hi @ynlx / @aleksandrkim61 ,

Is there any update on visualizing the 3D tracker's results? I can not found a suitable/easy repository to visualize the obtained results.

**Comment by ghost** [comment]
@ynlx @aleksandrkim61 Hello，could you offer the code to visualize the results, thanks very much!

**Comment by aleksandrkim61** [comment]
New update https://github.com/aleksandrkim61/EagerMOT#visualization

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
