### ISSUE TITLE
KITTI MOTS dataset

### ISSUE THREAD

**Issue by andreapereza2** [aleksandrkim61/EagerMOT#13]
Hi,

I would like to test this code with the KITTI MOTS dataset but it is not very clear to me how to do it, is it possible? In the article I read that you have tested with KITTI MOTS but then in the configuration it seems that it has been done with KITTI.

Thank you very much

**Comment by aleksandrkim61** [comment]
MOTS was a very old usage of this work. Please reopen and comment if you still need and I will try to dig for it.
