### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by zhaojieting** [aleksandrkim61/EagerMOT#14]
![2021-11-03 13-53-47屏幕截图](https://user-images.githubusercontent.com/53802668/140015312-e8de3993-1071-4774-9d7e-46749f485572.png)

Dear Kim:
        Thanks for your brilliant work, I ran the EagerMOT on Kitti dataset, got the result shown above , is that right? Why there is no matched instances?  
        Best wishes!

**Comment by zhaojieting** [comment]
I used the detection results  of PointGNN and Motsfusion_RRC.

**Comment by Alfa-Shashank** [comment]
Hello @zhaojieting, I also am trying on the same dataset inputs which are PointGNN and Motsfusion_RRC. Could you please explain how MotsFusion_RRC detections are that is about its folder structure? It has 29 folders each in detection and segmentation and some detection files in them. My question is what are these 29 parent folders?

**Comment by Alfa-Shashank** [comment]
I could run the script but after 29 sequences, it says file not found!

**Comment by Alfa-Shashank** [comment]
![Screenshot (214)](https://user-images.githubusercontent.com/55598466/171384768-4ceb5dd7-8178-4d43-a6c7-a1635ff9c500.png)
As there are only 29 npy files i m getting this error. Could you help me in understanding this?

**Comment by aleksandrkim61** [comment]
@Alfa-Shashank It says you are missing ego motion files, make sure you downloaded and unzipped them as written in https://github.com/aleksandrkim61/EagerMOT#how-to-set-up

@zhaojieting looks like you are missing or incorrectly parsed 2D detections. Go through your custom changes and debug to see what you get as your 2D detection inputs in the tracking code.

Closing for now
Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
