### ISSUE TITLE
Query on result for nuscenes data with centerpoint and mmdetection_cascade_x101 detections

### ISSUE THREAD

**Issue by gayathri81** [aleksandrkim61/EagerMOT#15]
Dear Kim, 
Thanks for sharing your code. I am trying to run tracking on **v1.0-mini** version of the nuScenes dataset downloaded from [here,](https://www.nuscenes.org/download) with the detections you provided in the [drive](https://drive.google.com/drive/folders/1MpAa9YErhAZNEJjIrC4Ky21YfNj2jatM) **centerpoint** and **mmdetection.** Gave SPLIT as mini_val and modified the val/test in the detections folder to min_val/min_test and ran the code to see the results.
I was getting below result which I couldn't understand. Please help me understand the tracking results and if the dataset and detections are properly provided.

**Console output after I ran run_tracking.py**:
![image](https://user-images.githubusercontent.com/92775047/141102045-9ba5e9e2-cb5e-4ee5-a450-b67d51e23bd2.png)

Thanks,
Gayathri.

**Comment by gayathri81** [comment]
running fresh removing the eagermot_workspace folder helped fixing this issue.

**Comment by SahilChachra** [comment]
Hello @gayathri81 . Were you able to visualize the results (the output json)? Can you guide me too?

Thanks,
Sahil.

**Comment by zzm-hl** [comment]
> 你好@gayathri81。您是否能够可视化结果（输出 json）？你也可以指导我吗？
> 
> 谢谢， 萨希尔。

I have the same problem ,have you solved it?
