### ISSUE TITLE
How to reproduce ego-motion files for KITTI?

### ISSUE THREAD

**Issue by fnozarian** [aleksandrkim61/EagerMOT#17]
Hello,
I tried to reproduce ego-motion npy files for the KITTI tracking sequences. I used both [kitti_to_rosbag](https://github.com/ethz-asl/kitti_to_rosbag/blob/master/kitti_to_rosbag/src/kitti_parser.cpp#L507) and [KITTI360Scripts](https://github.com/autonomousvision/kitti360Scripts/blob/master/kitti360scripts/devkits/convertOxtsPose/python/convertOxtsToPose.py) to convert oxts seq files to poses. I also transformed them into the rectified reference camera frame. However, as you can see in  [reproduced trajectory](https://i.imgur.com/tC1rPPD.png), [xyz view](https://i.imgur.com/MsYGp48.png) and [rpy view](https://i.imgur.com/qUPacov.png) images the reproduced trajectories are slightly different than yours. Can you please explain how did you generate the ego motions?

**Comment by gcaldarulo7** [comment]
Hi,
I encountered a similar issue when working on my MSc Thesis on autonomous driving as I'm trying to run EagerMOT on a custom dataset which I tried to put in the KITTI format. Could you explain if you managed to recreate the ego-motion file how it can be produced?

**Comment by aleksandrkim61** [comment]
Those files were generated using https://github.com/aljosaosep/sparse-scene-flow
If the format is different, that was just some `numpy` calls and then writing to disc. It was done too long ago and I do not have saved instructions, but that repo is the only software which was used.

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
