### ISSUE TITLE
Tentative Date for Release

### ISSUE THREAD

**Issue by turtleMaster20** [aleksandrkim61/EagerMOT#2]
Any tentative dates for the release of the code? 

The concept seems like a natural successor to previous methods and I am very 'Eager' to try it :D

**Comment by aleksandrkim61** [comment]
Just a couple more days at most, I did not have as much time to work on it as I thought. Please check in again then :)

**Comment by aleksandrkim61** [comment]
Had to spend time on other things, but it is up now :)

**Comment by turtleMaster20** [comment]
Thanks a lot... :D.... will definitely try it out
