### ISSUE TITLE
About running the testing split

### ISSUE THREAD

**Issue by gcaldarulo7** [aleksandrkim61/EagerMOT#22]
Hi, I've tried running the code on the KITTI testing split but we I do so the program returns the error: 
No such file or directory: 'data_kitti/testing\\label_02\\0001.txt'
I changed the split variable in the local_variable.py file and also run the adapt_kitti_motsfusion_input.py script as I'm using PointGNN and MOTSFusion for detections.
Also, is it possible to run the algorithm using 3D detections only without specifying the variable seg_source in the run_on_kitti function?
Thanks in advance

**Comment by aleksandrkim61** [comment]
By default it also outputs tracking evaluation. 
Simply comment out the line that uses `perform_tracking_for_eval` and anything else related to that

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
