### ISSUE TITLE
Question about AMOTP in ablation

### ISSUE THREAD

**Issue by tiffanyyk** [aleksandrkim61/EagerMOT#23]
Hi @aleksandrkim61, regarding the results in the paper, I noticed that the ablation study in Table IV using nuScenes dataset reports an AMOTP where higher is better. However, for the nuScenes benchmark and in their [provided code](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/tracking/evaluate.py), AMOTP is defined using center distance where lower is better. I'm wondering how the AMOTP in Table IV was computed. Was it using 3D IoU?
Thanks in advance!

**Comment by aleksandrkim61** [comment]
The AMOTP was taken directly from the official evaluation.
Perhaps the higher/lower is better was a mistake - will look at it
