### ISSUE TITLE
EagerMot result format

### ISSUE THREAD

**Issue by YCAyca** [aleksandrkim61/EagerMOT#26]
Hello, I try to visualize my EagerMOT resuts. I used prepared pointgnn as 3D inputs and RRC segmentations as 2D input. I obtain following result for an object tracked in a sequence:

0 1 Pedestrian 0 0 -1.000000 -1 -1 -1 -1 1.666817 0.743471 0.980450 6.358918 1.613495 8.489952 1.077119 4.558822 

What is the format of this output exactly? I used KITTI dataset so I assume it in kitti tracking format but the last value, which should be precision score in this case, is not compatible with precision score format ( which should be between 0-1). Can you give a brief explanation about this output format? For  example the 3D object dimensions and locations (from 11. to 16. value) are the 3d bounding box info in image or lidar space? 
Thanks!

**Comment by aleksandrkim61** [comment]
Check out https://github.com/JonathonLuiten/TrackEval/blob/master/docs/KITTI-format.txt
This should include all needed info, open the issue again if something concrete is unclear

Sorry for the late reply, was busy with other stuff and did not get proper notifications. Check out my latest work https://polarmot.github.io/
