### ISSUE TITLE
Visualization of the results

### ISSUE THREAD

**Issue by dpujol04** [aleksandrkim61/EagerMOT#27]
Hello!

In the README you say that you will create another repository to visualize the results. Was it created or not yet?

Thank you!

**Comment by ghost** [comment]
@dpujol04 Hello，have you realized visualization of the results? Could you share me your methods?

**Comment by aleksandrkim61** [comment]
Hey, I have a small script I used with this repo to visualise outputs. I will get to push it this weekend!

**Comment by aleksandrkim61** [comment]
Done, checkout https://github.com/aleksandrkim61/EagerMOT#visualization
Check out my latest work https://polarmot.github.io/
