### ISSUE TITLE
'MOTFrameNuScenes' object has no attribute 'bbox_3d_from_nu'

### ISSUE THREAD

**Issue by LouisShen233** [aleksandrkim61/EagerMOT#30]
Thank you for updating the visualization script!
When I use it to visualiztaion the result in nuscenes, comes out this error:

> Traceback (most recent call last):
  File "visualize.py", line 398, in <module>
    target_sequences=target_sequences, target_frame=20, result_json=json_to_parse, radius=0.06, save_img=True)
  File "visualize.py", line 114, in visualize_3d
    geometries_to_add = vis_mot_predictions_submitted(frame, params, all_colors, tracking_results, radius, world)
  File "visualize.py", line 229, in vis_mot_predictions_submitted
    bbox_internal = frame.bbox_3d_from_nu(bbox, bbox_label, world=True)
AttributeError: 'MOTFrameNuScenes' object has no attribute 'bbox_3d_from_nu'

Is there some solution for that?

**Comment by aleksandrkim61** [comment]
Fixed the missing method and ran the method with the latest repo pull. Should be good now 
Open a different issue if some other error pops up. Make sure to properly set your data paths in the calling code :)
