### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by freshwk** [aleksandrkim61/EagerMOT#7]
Thank you for your awesome work. I am trying to test your code in my computer but i am failed.My questions  are as follows. I would appreciate for your reply.
1、I modified SPLIT = 'testing' in local_variables.py to test the code. Is it right?
2、I want to use PointGnn and TrackRCNN. How should i modify the code?

**Comment by aleksandrkim61** [comment]
Hi!

1. The `SPLIT` variable refers to training/testing data splits for KITTI and train/val/test/... for NuScenes. So, you probably would want to have `training` in that variable to try to run the code in your environment and compare results.
2. To use specific detections, please download them from the links provided in the README. PointGNN and TrackRCNN need to be downloaded from their respective project pages. After downloading, simply put that data in some directory as described in the README and supply the path in `inputs/utils.py`. For PointGNN, you would change the `POINTGNN_DETS_DIR` variable and `SEGMENTATIONS_TRACKRCNN_DIR` for TrackRCNN.

Please carefully follow the instructions in [the README section](https://github.com/aleksandrkim61/EagerMOT#how-to-set-up), which answers both of these questions and has some further notes on how to run the code.

Feel free to open another issue if you have trouble with anything else!

**Comment by aleksandrkim61** [comment]
Added a clarifying sentence to the README about the `SPLIT` variable. Perhaps the original instruction is unclear if you are not used to how KITTI and NuScenes data is organized.
